### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by g33xter** [ustayready/CredSniper#11]
getting this error after command execution.
![screen shot 2017-11-03 at 23 48 36](https://user-images.githubusercontent.com/8503135/32403236-d2bf6c60-c0f1-11e7-9811-0899986b925b.png)

**Comment by DakotaNelson** [comment]
In the code, check out this portion:

https://github.com/ustayready/CredSniper/blob/d98f715307312c95c8e26ea9f94fb1429f61c18d/credsniper.py#L134-L140

You'll need to make sure that there are valid certificate files in those places. Can you double check to make sure those files exist?

Note that the full name of the certs will be something like `certs/example.com.cert.pem` depending on the hostname you're using.

If you run `install.sh` those certs *should* be created, but it looks like something went wrong.

**Comment by g33xter** [comment]
I'm getting that above error while installing credsniper.

**Comment by g33xter** [comment]
Those certs are not created in certs folder.

**Comment by ustayready** [comment]
If the certs are failing to be created, it's because you are either trying to generate certificates for a host not assigned to the server you are running it on or Let's Encrypt is unable to communicate with your server during the challenge/response process.
