### ISSUE TITLE
how can I login ? ( i have 2fa sms number )

### ISSUE THREAD

**Issue by Phoenix1112** [ustayready/CredSniper#22]
hello. i am testing credsniper.  

i have " email name -  email password - 2fa sms number

, i dont understand now..  if I try to log in with an email and password, I will send sms again ..If i send sms again,how sms number on hand will work

do not have a token number like evilginx ???can i go the mail box with cookies like evilginx ???

now can you tell me how to login with the sms code ??

**Comment by ustayready** [comment]
CredSniper captures the email, password and 2fa token assuming the target supplies the details to the phishing portal. Evilnginx is a proxy. After you receive the email/password/2fa token you login manually using your browser.

Closing because this is not an issue
