### ISSUE TITLE
another ip address looks

### ISSUE THREAD

**Issue by Phoenix1112** [ustayready/CredSniper#23]
The site is active after installation with install.sh file ....ip address of visitors to the site appears at the terminal...I tested myself and it seemed my ip address...but different ip addresses started to appear..
in this experiment first the french ip address was seen then the american ip address was seen...
I just opened the site yet new and the site has been active for only 20 minutes..there is no one who knows the name of the site other than me... 

why does someone else's ip address look like on terminal ?? do somebody have the right to access this program ??can you access the information of people who use this program @ustayready 

i think when my site is active you can see it and you can enter my site and look at the passwords @ustayready

**Comment by ustayready** [comment]
People regularly scan the internet for web ports and unless you're on a dedicated IP address, IP addresses are rotated from customer to customer based on available resources. Another thing to consider is if you used an SSL certificate comma the certificate transparency project is regularly monitored by people and attackers alike which means when a new certificate is registered people know how to find the site. It's not uncommon for new credsniper instances to be visited by bots immediately after launching. This is especially true if you obtained an IP address that was previously used for a website where links to that website might still be active on other sites comma like a backlink.

GitHub does show me who forks and stars the project but that information is available for everybody on public repos. I do not have the ability to see how credsniper is used or any information it harvests.

Hope this helps!

**Comment by ustayready** [comment]
By the way, all of the code is 100% open source, feel free to comb through it if you have concerns about security.

**Comment by Phoenix1112** [comment]
thank you for everything....i am believe you....this program very nice.....When the sms code goes to the victim's phone, the last 2 digits of the phone number are misspelled. Is it because it is a phishing attack??

sms code send 
**********80 

my phone last numbers not 80. ...

can you change last numbers whith real last numbers ?

or can we change it because it is a phishing attack?

**Comment by ustayready** [comment]
The SMS goes to whatever phone number is on file for the account being phished. The numbers displayed to the user are the same numbers that Google shows to the user when they are authenticating. CredSniper literally pulls out the numbers from the authentication on the back-end and renders it in the phishing page showed to the target.

**Comment by Phoenix1112** [comment]
yes ... sms code is coming... 

now i try again the phone number does not write the last 2 numbers in the place
I tried this morning , the last 2 numbers of the phone number were 80 and it was wrong

wrong
(***)*** *80

true
**********79
I tried now but did not write anything (...)..... .... ....
![2](https://user-images.githubusercontent.com/42475284/45049098-45ebfd00-b086-11e8-8f36-0b4bb2c0d224.png)

--------------------------------------------------------------------------------------------------------------------------------------

other problem...

credsniper.py is not working true ??

only i am using install.sh

![1](https://user-images.githubusercontent.com/42475284/45049198-94999700-b086-11e8-8b18-87e5a1226841.png)

**Comment by ustayready** [comment]
If the numbers are not showing up, it's because something with the back-end authentication that Google is doing. Something is causing Google to flag the authentication as risky and is possibly either locking out attempts or requesting more information before completing the authentication. This happens when the wrong credentials are supplied from an IP over and over, multiple failed attempts occur on an account, or if the IP is flagged as suspicious. 
Side note, you only need to run install.sh once. After everything is up and running, you just use: python credsniper.py

**Comment by Phoenix1112** [comment]
python credsniper.py is not working.... i am using install.sh 


root@CyberTheReapeR:~/CredSniper-master# python credsniper.py --module gmail --twofactor --port 443 --ssl --verbose --final https://www.youtube.com/c/teknolojivesavunma --hostname accounts.google.com.loginin.cf

Traceback (most recent call last):
  File "credsniper.py", line 118, in <module>
    cs = CredSniper()
  File "credsniper.py", line 25, in __init__
    self.prepare_module()
  File "credsniper.py", line 35, in prepare_module
    loader=PackageLoader('credsniper', package),
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 224, in __init__
    provider = get_provider(package_name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 348, in get_provider
    __import__(moduleOrReq)
  File "/root/CredSniper-master/credsniper.py", line 118, in <module>
    cs = CredSniper()
  File "/root/CredSniper-master/credsniper.py", line 25, in __init__
    self.prepare_module()
  File "/root/CredSniper-master/credsniper.py", line 39, in prepare_module
    self.module = importlib.import_module(module_path).load(self.enable_2fa)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/CredSniper-master/modules/gmail/gmail.py", line 193
SyntaxError: Non-ASCII character '\xe2' in file /root/CredSniper-master/modules/gmail/gmail.py on line 193, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ustayready** [comment]
Not sure the environment you are operating in. Is this Kali? It's only been tested on Ubuntu 16.04. Also, make sure the Python virtual environment has been activated. For instance: source /root/CredSniper-master/bin/activate

**Comment by Phoenix1112** [comment]
OMG  ---  it is worked now >>>>>   source /root/CredSniper-master/bin/activate 

i am usng kali linux....(kde desktop)......thank you for everything.... you are big man....

![yeni_1](https://user-images.githubusercontent.com/42475284/45050490-1b9c3e80-b08a-11e8-846a-b010ea24302e.png)


![yeni_2](https://user-images.githubusercontent.com/42475284/45050523-2fe03b80-b08a-11e8-8dbf-f01643a1fe2c.png)

**Comment by ustayready** [comment]
No problem. Glad it's up and working.
